package com.acme.kmp.compose.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable

/** Defines the theme for your app.
 *
 * This is included within [com.acme.kmp.compose.App].
 *
 * This is `internal` since [App][com.acme.kmp.compose.App] is the only entry point other platforms
 * should care about.
 * Also, any `@Preview` should only be defined within `kmpCompose` module.
 *
 * If there are specific platform requirements and motivation to define `@Composable` in other modules, you
 * should use `AppTheme` to wrap such components to verify their correct rendering.
 *
 * @param colorScheme Color scheme. Defaults to either [Theme.darkScheme] or [Theme.lightScheme].
 * @param content You app [Composable]s.
 */
@Composable
internal fun AppTheme(
    colorScheme: ColorScheme = if (isSystemInDarkTheme()) Theme.darkScheme else Theme.lightScheme,
    content: @Composable () -> Unit,
) {
    MaterialTheme(
        colorScheme = colorScheme,
        typography = AppTypography,
        content = content,
    )
}

/** Themes to use.
 * Note that this is also used within module `app-android/src/main/kotlin/com/acme/mobile/app/MainActivity.kt`
 *
 * All Themes were generated by
 * [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/?primary=%23415f91),
 * plus some refactoring to keep everything organized.
 *
 * @see AppTheme
 * @see Palette
 */
object Theme {
    /** Using [lightColorScheme] with all our [Palette] colors.
     *
     * Note that all arguments are specified when calling [lightColorScheme].
     * Commented ones are using the default values.
     * This was included just to track future changes.
     */
    val lightScheme =
        lightColorScheme(
            primary = Palette.Light.primaryLight,
            onPrimary = Palette.Light.onPrimaryLight,
            primaryContainer = Palette.Light.primaryContainerLight,
            onPrimaryContainer = Palette.Light.onPrimaryContainerLight,
            inversePrimary = Palette.Light.inversePrimaryLight,
            secondary = Palette.Light.secondaryLight,
            onSecondary = Palette.Light.onSecondaryLight,
            secondaryContainer = Palette.Light.secondaryContainerLight,
            onSecondaryContainer = Palette.Light.onSecondaryContainerLight,
            tertiary = Palette.Light.tertiaryLight,
            onTertiary = Palette.Light.onTertiaryLight,
            tertiaryContainer = Palette.Light.tertiaryContainerLight,
            onTertiaryContainer = Palette.Light.onTertiaryContainerLight,
            background = Palette.Light.backgroundLight,
            onBackground = Palette.Light.onBackgroundLight,
            surface = Palette.Light.surfaceLight,
            onSurface = Palette.Light.onSurfaceLight,
            surfaceVariant = Palette.Light.surfaceVariantLight,
            onSurfaceVariant = Palette.Light.onSurfaceVariantLight,
            // surfaceTint = primary,
            inverseSurface = Palette.Light.inverseSurfaceLight,
            inverseOnSurface = Palette.Light.inverseOnSurfaceLight,
            error = Palette.Light.errorLight,
            onError = Palette.Light.onErrorLight,
            errorContainer = Palette.Light.errorContainerLight,
            onErrorContainer = Palette.Light.onErrorContainerLight,
            outline = Palette.Light.outlineLight,
            outlineVariant = Palette.Light.outlineVariantLight,
            scrim = Palette.Light.scrimLight,
            surfaceBright = Palette.Light.surfaceBrightLight,
            surfaceContainer = Palette.Light.surfaceContainerLight,
            surfaceContainerHigh = Palette.Light.surfaceContainerHighLight,
            surfaceContainerHighest = Palette.Light.surfaceContainerHighestLight,
            surfaceContainerLow = Palette.Light.surfaceContainerLowLight,
            surfaceContainerLowest = Palette.Light.surfaceContainerLowestLight,
            surfaceDim = Palette.Light.surfaceDimLight,
            // primaryFixed = ColorLightTokens.PrimaryFixed,
            // primaryFixedDim = ColorLightTokens.PrimaryFixedDim,
            // onPrimaryFixed = ColorLightTokens.OnPrimaryFixed,
            // onPrimaryFixedVariant = ColorLightTokens.OnPrimaryFixedVariant,
            // secondaryFixed = ColorLightTokens.SecondaryFixed,
            // secondaryFixedDim = ColorLightTokens.SecondaryFixedDim,
            // onSecondaryFixed = ColorLightTokens.OnSecondaryFixed,
            // onSecondaryFixedVariant = ColorLightTokens.OnSecondaryFixedVariant,,
            // tertiaryFixed = ColorLightTokens.TertiaryFixed,
            // tertiaryFixedDim = ColorLightTokens.TertiaryFixedDim,
            // onTertiaryFixed = ColorLightTokens.OnTertiaryFixed,
            // onTertiaryFixedVariant = ColorLightTokens.OnTertiaryFixedVariant,
        )

    /** Using [darkColorScheme] with all our [Palette] colors.
     *
     * Note that all arguments are specified when calling [darkColorScheme].
     * Commented ones are using the default values.
     * This was included just to track future changes.
     */
    val darkScheme =
        darkColorScheme(
            primary = Palette.Dark.primaryDark,
            onPrimary = Palette.Dark.onPrimaryDark,
            primaryContainer = Palette.Dark.primaryContainerDark,
            onPrimaryContainer = Palette.Dark.onPrimaryContainerDark,
            inversePrimary = Palette.Dark.inversePrimaryDark,
            secondary = Palette.Dark.secondaryDark,
            onSecondary = Palette.Dark.onSecondaryDark,
            secondaryContainer = Palette.Dark.secondaryContainerDark,
            onSecondaryContainer = Palette.Dark.onSecondaryContainerDark,
            tertiary = Palette.Dark.tertiaryDark,
            onTertiary = Palette.Dark.onTertiaryDark,
            tertiaryContainer = Palette.Dark.tertiaryContainerDark,
            onTertiaryContainer = Palette.Dark.onTertiaryContainerDark,
            background = Palette.Dark.backgroundDark,
            onBackground = Palette.Dark.onBackgroundDark,
            surface = Palette.Dark.surfaceDark,
            onSurface = Palette.Dark.onSurfaceDark,
            surfaceVariant = Palette.Dark.surfaceVariantDark,
            onSurfaceVariant = Palette.Dark.onSurfaceVariantDark,
            // surfaceTint = primary,
            inverseSurface = Palette.Dark.inverseSurfaceDark,
            inverseOnSurface = Palette.Dark.inverseOnSurfaceDark,
            error = Palette.Dark.errorDark,
            onError = Palette.Dark.onErrorDark,
            errorContainer = Palette.Dark.errorContainerDark,
            onErrorContainer = Palette.Dark.onErrorContainerDark,
            outline = Palette.Dark.outlineDark,
            outlineVariant = Palette.Dark.outlineVariantDark,
            scrim = Palette.Dark.scrimDark,
            surfaceBright = Palette.Dark.surfaceBrightDark,
            surfaceContainer = Palette.Dark.surfaceContainerDark,
            surfaceContainerHigh = Palette.Dark.surfaceContainerHighDark,
            surfaceContainerHighest = Palette.Dark.surfaceContainerHighestDark,
            surfaceContainerLow = Palette.Dark.surfaceContainerLowDark,
            surfaceContainerLowest = Palette.Dark.surfaceContainerLowestDark,
            surfaceDim = Palette.Dark.surfaceDimDark,
            // primaryFixed = ColorDarkTokens.PrimaryFixed,
            // primaryFixedDim = ColorDarkTokens.PrimaryFixedDim,
            // onPrimaryFixed = ColorDarkTokens.OnPrimaryFixed,
            // onPrimaryFixedVariant = ColorDarkTokens.OnPrimaryFixedVariant,
            // secondaryFixed = ColorDarkTokens.SecondaryFixed,
            // secondaryFixedDim = ColorDarkTokens.SecondaryFixedDim,
            // onSecondaryFixed = ColorDarkTokens.OnSecondaryFixed,
            // onSecondaryFixedVariant = ColorDarkTokens.OnSecondaryFixedVariant,
            // tertiaryFixed = ColorDarkTokens.TertiaryFixed,
            // tertiaryFixedDim = ColorDarkTokens.TertiaryFixedDim,
            // onTertiaryFixed = ColorDarkTokens.OnTertiaryFixed,
            // onTertiaryFixedVariant = ColorDarkTokens.OnTertiaryFixedVariant,
        )
}

/* Schemes generated by Material Theme Builder for different contrast schemes.
 * Not used, but kept for reference.
 private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
 )

 private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
 )

 private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
 )

 private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
 )
*/
